### ISSUE TITLE
Cannot create persistent volume claim

### ISSUE THREAD

**Issue by hunghoang** [IBM/ibm-block-csi-driver#129]
Hi,
I'm using Kubernetes and using this driver to create persistent volume.
But when create persistent volume claim, I get this error:
Warning  ProvisioningFailed    39s (x15 over 34m)     block.csi.ibm.com_ibm-block-csi-controller-0_7b53db65-5c51-11ea-903d-ce189fa485ad  failed to provision volume with StorageClass "gold": rpc error: code = Internal desc = an internal exception occurred : Credential error has occurred while connecting to endpoint : 172.16.1.3

Do I need to install IBM Virtualize to make it work?
My Env:
- Kubernetes 1.17
- OS: Centos 7
- SAN: V5010

Please help?

**Comment by hunghoang** [comment]
I can connect using https://github.com/IBM/pysvc with the same Credential. It is the problem related to Base64?

**Comment by 27149chen** [comment]
@hunghoang , can you share your detailed steps to deploy the driver and reproduce this issue?
Currently, Kubernetes 1.17 is not officially supported,  please do not use it in production.
Please check the log of sts ibm-block-csi-controller, and attach the errors here.

**Comment by hunghoang** [comment]
Just change the secret by using plain text password and it works:

array-secret.yaml:

`kind: Secret
apiVersion: v1
metadata:
  name: san-secret-test
  namespace: kube-system
type: Opaque
stringData:
  management_address: 172.16.1.4 # Array management addresses
  username: abcd            # Array username
  password: xyz
#data:
#  password: <base64 value>  `

**Comment by 27149chen** [comment]
@hunghoang, do you need other helps? if not, please close this issue.

**Comment by hunghoang** [comment]
OK
But the document should be updated

**Comment by vmorris** [comment]
I also just ran into this issue - using the `data:password` field and base64 encoding the password failed, but setting it in plaintext in the `stringData:password` field worked.

There's a bug here, either the documentation is incorrect or the driver needs to be fixed.
https://www.ibm.com/docs/en/stg-block-csi-driver/1.7.0?topic=configuration-creating-secret

**Comment by oriyarde** [comment]
@vmorris @hunghoang the driver controller [receives the data decoded](https://github.com/IBM/ibm-block-csi-driver/blob/2a89451f916307fff10640243a0e5782360d8a9c/controller/controller_server/utils.py#L76) [from the k8s sidecar](https://github.com/kubernetes-csi/external-provisioner/blob/7ae61466a611061ba70da2679358c8bfc8546b6f/pkg/controller/controller.go#L1696).
the sidecar gets the data [decoded from the k8s go client](https://github.com/kubernetes/client-go/blob/2f5d8b0c528db5467159baccddc3f634fcea0747/applyconfigurations/core/v1/secret.go#L36) it uses.
we are unable to reproduce this issue, so it is not clear what should be updated in our docs.

please try encoding your password using the following command (replacing `demo-password` with your password):
`python -c "import base64; print(base64.b64encode('demo-password'.encode()).decode())"`

is the output the same as the base64-encoded data which failed?
if it is not the same:
1. try to use the new base64-encoded data
2. try to decode failing base64-encoded data and compare the output with your plaintext password, using the following command:
`python -c "import base64; print(repr(base64.b64decode('UGFzc3cwcmQK').decode()).strip("'"))"`

please report back.

**Comment by vmorris** [comment]
Aha, thanks for the explanation. I was using `base64` and the linux command line to encode my password and indeed, it's different output from the python method:

```
vmorris@tpp53:~ $ python -c "import base64; print(base64.b64encode('passw0rd'.encode()).decode())"
cGFzc3cwcmQ=
vmorris@tpp53:~ $ echo passw0rd | base64
cGFzc3cwcmQK
```

**Comment by vmorris** [comment]
This is better, lesson learned today. Thanks very much!

```
vmorris@tpp53:~ $ echo passw0rd | tr -d \\n | base64
cGFzc3cwcmQ=
```
