### ISSUE TITLE
IBM block storage CSI driver for OCP ppc64le

### ISSUE THREAD

**Issue by ticlazau** [IBM/ibm-block-csi-driver#259]
Hello,

according to provided documentation, only OpenShift v4.3 is supported on IBM PowerPC, are there any plans to support OpenShift v4.6 on IBM PowerPC (ppc64le)?

Thx,
FM

**Comment by erantzabari** [comment]
Yes.
We will support OCP 4.5 on IBM PowerPC on Q4/2020 version.
We will support OCP 4.6 on IBM PowerPC on Q1/2021 version.
