### ISSUE TITLE
Will IBM block storage CSI driver be supported in OCP4.6 on IBM Z?

### ISSUE THREAD

**Issue by jwyoon-darum** [IBM/ibm-block-csi-driver#289]
Hello!

I am now trying to use OCP4.6 on IBM Z.
I tried installing IBM block storage CSI driver 1.4.0, and even pv and pvc were installed, but the POD is not mounted.
Is that because the provided documentation says that only OCP4.5 is supported?
If so, I am curious when it will be supported in OCP4.6.

Thank you.

OCP 4.6 equipment
-IBM Z

Storage equipment
-FS7200

**Comment by jwyoon-darum** [comment]
I tried installing with OCP4.5 because it was a problem with the OCP version, but the same problem appeared.

**Comment by erantzabari** [comment]
We added support in 1.4.0 over OCP 4.6.
CSI Block version 1.5.0 which will be released in the up coming Thursday will support OCP 4.6 and OCP 4.7.
