### ISSUE TITLE
Feature request: Support for Hyperswap/stretch configurations

### ISSUE THREAD

**Issue by sandori01** [IBM/ibm-block-csi-driver#329]
It would be nice to have support for Spectrum Virtualize HyperSwap and SVC Stretch cluster configurations. As of Spectrum Virtualize v8.3.1 hyperswap volumes can be created with a single command (no extra configuration is needed) specifying both pools at the command line. (I haven't checked if the same applies to stretch volumes)
As far as I was able to understand, the code assembles SVCTASK command to create the volume, and if we specify the two pools involved in the operation, the controller blindly executes and creates a hyperswap volume. I see no problem specifying the pools as "pool1:pool2" in the storage class definition so basically, this could work. Unfortunatelly I do not have a test environment where I would be able to test it.

Could you examine the possibility of including support for this kind of environments as well?

Regards,
Imre

**Comment by roysahar-ibm** [comment]
@sandori01 , thank you for your comment.
Hyperswap and stretch volumes features are on our CSI driver road map. We started with design talks part of replication feature. Currently no implementation for hyperswap and stretch volumes. We will update when we will have the version with these features inside.

**Comment by roysahar** [comment]
@sandori01 I am happy to update that we delivered CSI 1.8.0 that introduced with Hyperswap support, see our documentation - https://www.ibm.com/docs/en/stg-block-csi-driver/1.8.0?topic=notes-whats-new-in-180.

**Comment by roysahar** [comment]
https://www.ibm.com/docs/en/stg-block-csi-driver/1.8.0?topic=notes-whats-new-in-180
