### ISSUE TITLE
CSI driver for Spectrum Virtualize 8.4.2

### ISSUE THREAD

**Issue by mjosipovic1979** [IBM/ibm-block-csi-driver#398]
Hi

we tried to use CSI driver (1.5.1) in k8s (1.19) using iscsi to connect to IBM FS5200 which is running 8.4.2 code.
8.4.2 code remove some lsipport command and controller can not get iscsi target

I1104 09:15:42.841714       1 csi_handler.go:226] Error processing "csi-bf395e391731114baec5c345c92ec0a21d82e4ed6158ddb9c5d8f84a6e3d76f2": failed to attach: rpc error: code = NotFound desc = Could not find iSCSI targets for endpoint: 10.7.60.100

we found that ifix can be installed on FlashSystem and investigating that option
https://www.ibm.com/support/pages/support-iscsi-iser-configuration-interfaces-spectrum-virtualize-842

but we think that support should be added to CSI Driver set.
thanks

regards
Mirko

**Comment by mjosipovic1979** [comment]
hi

any news?

**Comment by erantzabari** [comment]
Hi @mjosipovic1979 ,

Since there was a command change in Virtualize 8.4.2 previous versions of CSI would need to have iFix for Virtualize 8.4.2.
This issue is already been solve in CSI 1.7.0 and above.

FYI
