### ISSUE TITLE
Network ports requirement from csi to storage array  

### ISSUE THREAD

**Issue by lborek** [IBM/ibm-block-csi-driver#617]
Hi,
We need to open firewall port (assuming port 22 is used for management) between k8s cluster and storage array management IP. Which pod needs that traffic? Or all of them? 

ibm-block-csi-controller-0 (pods network)
ibm-block-csi-node-* ( hostNetwork)
ibm-block-csi-operator-* (pods network) 

Thanks.

**Comment by kasserater** [comment]
ibm-block-csi-controller-0
